ScrollReveal().reveal('.title');
ScrollReveal().reveal('.a1',{ delay: 400 });
ScrollReveal().reveal('.a2',{ delay: 700 });
ScrollReveal().reveal('.image-menu',{ delay: 900 });
ScrollReveal().reveal('.title2',{ delay: 1200});

ScrollReveal().reveal('.carousel');
ScrollReveal().reveal('.carousel-item',{ delay: 200});
ScrollReveal().reveal('.container-aboute');
ScrollReveal().reveal('.title-about');
ScrollReveal().reveal('.container-description');
ScrollReveal().reveal('.img-one',{ delay: 900});
ScrollReveal().reveal('.img-two',{ delay: 1200});
ScrollReveal().reveal('.img-three',{ delay: 1500});
ScrollReveal().reveal('.img-four',{ delay: 1800});
ScrollReveal().reveal('.container-form',{ delay: 200});
ScrollReveal().reveal('.title-form',{ delay: 400});
ScrollReveal().reveal('.formulario',{ delay: 600});
ScrollReveal().reveal('.c-input',{ delay: 800});
ScrollReveal().reveal('.c-input2',{ delay: 1000});
ScrollReveal().reveal('.message',{ delay: 1200});